export const MUSEUMS = {
  british_museum: {
    id: "british_museum",
    name: "British Museum",
    city: "London",
    lat: 51.519,
    lng: -0.127,
    color: [50, 70, 170],
    address: "Great Russell St, London WC1B 3DG, UK",
    photo: "https://esri-imagery-apps.s3.amazonaws.com/apps/artifact-explorer/images/british_museum.jpg",
    url: "https://www.britishmuseum.org",
  },
  met: {
    id: "met",
    name: "The Met",
    city: "New York",
    lat: 40.779,
    lng: -73.963,
    color: [150, 50, 150],
    address: "1000 Fifth Avenue, New York, NY 10028, USA",
    photo: "https://esri-imagery-apps.s3.amazonaws.com/apps/artifact-explorer/images/met.jpg",
    url: "https://www.metmuseum.org",
  },
  louvre: {
    id: "louvre",
    name: "Louvre",
    city: "Paris",
    lat: 48.861,
    lng: 2.336,
    color: [0, 160, 190],
    address: "Rue de Rivoli, 75001 Paris, France",
    photo: "https://esri-imagery-apps.s3.amazonaws.com/apps/artifact-explorer/images/louvre.jpg",
    url: "https://www.louvre.fr",
  },
  smithsonian: {
    id: "smithsonian",
    name: "Smithsonian",
    city: "Washington DC",
    lat: 38.888,
    lng: -77.026,
    color: [0, 112, 68],
    address: "1000 Jefferson Dr SW, Washington, DC 20560, USA",
    photo: "https://esri-imagery-apps.s3.amazonaws.com/apps/artifact-explorer/images/smithsonian.jpg",
    url: "https://www.si.edu",
  },
};
